// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scraping_Egy_Bus.Data;

#nullable disable

namespace Scraping_Egy_Bus.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251226105910_addMainTables")]
    partial class addMainTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.AdditionalTripData", b =>
                {
                    b.Property<int>("TripDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripDataId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("TripDataId");

                    b.HasIndex("TripId")
                        .HasDatabaseName("IX_AdditionalTripData_Trip");

                    b.ToTable("AdditionalTripData");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.BusType", b =>
                {
                    b.Property<int>("BusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusTypeId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("BusTypeId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_BusType_Company");

                    b.HasIndex("TypeName")
                        .HasDatabaseName("IX_BusType_Name");

                    b.ToTable("BusTypes");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("CityId");

                    b.HasIndex("CityName")
                        .IsUnique()
                        .HasDatabaseName("UX_City_Name");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyName")
                        .IsUnique()
                        .HasDatabaseName("UX_Company_Name");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Company_Active");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("StationId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StationName")
                        .HasDatabaseName("IX_Station_Name");

                    b.HasIndex("CityId", "CompanyId")
                        .HasDatabaseName("IX_Station_City_Company");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<DateTime?>("ArrivalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArrivalStationId")
                        .HasColumnType("int");

                    b.Property<int?>("BusTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartureStationId")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScrapedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TripId");

                    b.HasIndex("ArrivalStationId");

                    b.HasIndex("BusTypeId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Trip_Active");

                    b.HasIndex("CompanyId", "DepartureDateTime")
                        .HasDatabaseName("IX_Trip_Company_Date");

                    b.HasIndex("DepartureStationId", "ArrivalStationId", "DepartureDateTime")
                        .HasDatabaseName("IX_Trip_Search");

                    b.HasIndex("CompanyId", "DepartureStationId", "ArrivalStationId", "DepartureDateTime")
                        .IsUnique()
                        .HasDatabaseName("UX_Trip_Unique");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.TripStop", b =>
                {
                    b.Property<int>("TripStopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripStopId"));

                    b.Property<TimeSpan?>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int?>("StopOrder")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TripStopId");

                    b.HasIndex("StationId");

                    b.HasIndex("TripId")
                        .HasDatabaseName("IX_TripStop_Trip");

                    b.HasIndex("TripId", "StationId")
                        .IsUnique()
                        .HasDatabaseName("UX_TripStop_Trip_Station");

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Models.TempTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromCity")
                        .HasColumnType("int");

                    b.Property<string>("FromCityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ToCity")
                        .HasColumnType("int");

                    b.Property<string>("ToCityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TempTrips");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.AdditionalTripData", b =>
                {
                    b.HasOne("Scraping_Egy_Bus.Entities.Trip", "Trip")
                        .WithMany("AdditionalData")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.BusType", b =>
                {
                    b.HasOne("Scraping_Egy_Bus.Entities.Company", "Company")
                        .WithMany("BusTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.Station", b =>
                {
                    b.HasOne("Scraping_Egy_Bus.Entities.City", "City")
                        .WithMany("Stations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scraping_Egy_Bus.Entities.Company", "Company")
                        .WithMany("Stations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.Trip", b =>
                {
                    b.HasOne("Scraping_Egy_Bus.Entities.Station", "ArrivalStation")
                        .WithMany("ArrivalTrips")
                        .HasForeignKey("ArrivalStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scraping_Egy_Bus.Entities.BusType", "BusType")
                        .WithMany("Trips")
                        .HasForeignKey("BusTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Scraping_Egy_Bus.Entities.Company", "Company")
                        .WithMany("Trips")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scraping_Egy_Bus.Entities.Station", "DepartureStation")
                        .WithMany("DepartureTrips")
                        .HasForeignKey("DepartureStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalStation");

                    b.Navigation("BusType");

                    b.Navigation("Company");

                    b.Navigation("DepartureStation");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.TripStop", b =>
                {
                    b.HasOne("Scraping_Egy_Bus.Entities.Station", "Station")
                        .WithMany("TripStops")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scraping_Egy_Bus.Entities.Trip", "Trip")
                        .WithMany("TripStops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.BusType", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.City", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.Company", b =>
                {
                    b.Navigation("BusTypes");

                    b.Navigation("Stations");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.Station", b =>
                {
                    b.Navigation("ArrivalTrips");

                    b.Navigation("DepartureTrips");

                    b.Navigation("TripStops");
                });

            modelBuilder.Entity("Scraping_Egy_Bus.Entities.Trip", b =>
                {
                    b.Navigation("AdditionalData");

                    b.Navigation("TripStops");
                });
#pragma warning restore 612, 618
        }
    }
}
